[project]
name = "image-builder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.0.0",
    "pyyaml>=6.0.2",
    "typer>=0.15.2",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
